# directory containing samples' folders with fastq.gz files.
# data/directory/file.fastq.gz by default. Otherwise, you can provide this directory with
#  --config input_dir=<INPUT_DIR_PATH> when running snakemake
input_dir:
  Data
#Directory containing seperate .fasta files for each of the reference genomes
seperated_genomes_dir:
  resources/genomes/seperated
#directory containing the combined .fasta file containing all genomes.
genomes_dir:
  resources/genomes/
# directory with the sortmerna database
sortmerna_db_dir:
  resources/sortmerna_db
# files expected to be inside the sortmerna database directory 
sortmerna_db_files:
  rfam-5.8s-database-id98.fasta: rfam-5.8s-database-id98.fasta
  rfam-5s-database-id98.fasta: rfam-5s-database-id98.fasta
  silva-arc-16s-id95.fasta: silva-arc-16s-id95.fasta
  silva-arc-23s-id98.fasta: silva-arc-23s-id98.fasta
  silva-bac-16s-id90.fasta: silva-bac-16s-id90.fasta
  silva-bac-23s-id98.fasta: silva-bac-23s-id98.fasta

#full path to file containing Gene demarkations in SAF format  
gene_annotation_file:
  resources/genes/seperatedCrAssPhageGeneAnnotation.table
  
#START of autogenerated part of the config file;

samples:
  ERR2088987: Data/ERR2088987/ERR2088987.fastq
  SRR2992971: Data/SRR2992971/SRR2992971_1.fastq,Data/SRR2992971/SRR2992971_2.fastq